MODEL:
  FREEZE_BACKBONE:
    2D: false
    3D: false
  VERSION:  yowo_v2_nano
  RESUME: # '/Users/sylvaingrs/Documents/Github/DeepWDT/src/epoch_10.pth'
  CONF_THRESH: 0.01
  IOU_THRESH: 0.5
  NMS_THRESH: 0.5
  TOP_K: 10
  CENTER_SAMPLING_RADIUS: 2.5

TRAIN:
  AUGMENTATION:
    EXPOSURE: 1.5
    HUE: 0.1
    JITTER: 0.2
    SATURATION: 1.5
  BATCH_SIZE: 16
  DATASET:
    NAME: bengaluru_01
    CLASS: ['Dancing']
    IMAGE_SIZE: 224
    LEN_CLIP: 5
    CENTERED_CLIP: true
  DEVICE: gpu
  GPU: [0,]
  MAX_EPOCH: 20
  MLFLOW: true
  SOLVER:
    ACCUMULATE: 1
    BASE_LR: 0.00005
    MIN_LR_RATIO: 0.25
    WARMUP_EPOCH: 1
    NO_DECREASE_LR_EPOCH: 5
    OPTIMIZER: adamw
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    WARMUP: linear
    WARMUP_FACTOR: 0.00066667
    WP_ITER: 500
    LOSS:
      CONF_WEIGHT: 1
      CLS_WEIGHT: 1
      REG_WEIGHT: 5
      FOCAL_LOSS: false
  NUM_WORKERS: 8

EVAL:
  BATCH_SIZE: 8
  NUM_WORKERS: 8
  TRACKING_METHOD: SORT
  SPLIT: val

INFER:
  BATCH_SIZE: 8
  DATASET:
  THRESHOLD:
  TRACKING_METHOD: SORT
  WEIGHTS: ''
