AUGMENTATION:
  EXPOSURE: 1.5
  HUE: 0.1
  JITTER: 0.2
  SATURATION: 1.5
BATCH_SIZE:
  TRAIN: 8
  EVAL: 8
CENTER_SAMPLING_RADIUS: 2.5
CLASSES: 2
CONF_THRESH: 0.01
DATASET: training_dataset
DEVICE: cpu
DISTRIBUTION:
  DISTRIBUTED: false
  SYBN: false
  WORLD SIZE: 1
FREEZE_BACKBONE_2D: false
FREEZE_BACKBONE_3D: false
IMAGE_SIZE: 224
IOU_THRESH: 0.5
GROUND_TRUTH:
GPU: [0,]
LEN_CLIP: 16
LOSS_CONF_WEIGHT: 1
LOSS_CLS_WEIGHT: 1
LOSS_REG_WEIGHT: 5
FOCAL_LOSS: false
MAX_EPOCH: 10
MLFLOW: true
MULTI_HOT: false
NMS_THRESH: 0.5
NUM_WORKERS: 1
RESUME: false
SAMPLING_RATE: 1
SOLVER:
  ACCUMULATE: 1
  BASE_LR: 0.00005
  MIN_LR_RATIO: 0.25
  WARMUP_EPOCH: 1
  NO_DECREASE_LR_EPOCH: 7
  OPTIMIZER: adamw
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WARMUP: linear
  WARMUP_FACTOR: 0.00066667
  WP_ITER: 500
TOP_K: 10
MODEL_VERSION: yowo_v2_nano