eval:
  device: cuda
  weights: C:\Users\CREST\Documents\GitHub\DeepWDT\runs\train\250709-160557-tops-chimp-3074\weights\epoch_8.pth
#  weights: C:\Users\CREST\Documents\GitHub\DeepWDT\runs\train\250701-231200-fit-cattle-5645\weights\epoch_20.pth
#  weights: C:\Users\CREST\Documents\GitHub\DeepWDT\runs\train\250706-212655-living-panda-5489\weights\epoch_20.pth
  dataset:
#    name: apis_dorsata_01
    name: apis_dorsata_x_mellifera_01
    image_size: [224]
    len_clip: 32
    classes: ['Dancing']
    centered_clip: false
  model:
    name: 'yowo'
    backbone_2d:
      name: 'yolo_free_nano'
      frozen: false
      pretrained: true
      stride: [8,16,32]
    backbone_3d:
      name: 'shufflenetv2'
      frozen: false
      pretrained: true
      memory_momentum: 0.9
      model_size: "1.0x"
    center_sampling_radius: 2.5
    confidence_threshold: 0.01
    nms_threshold: 0.5
    top_k: 10
    head_dim: 64
    head_norm: BN
    head_act: lrelu
    num_cls_heads: 2
    num_reg_heads: 2
    head_depthwise: true
  batch_size: 32
  num_workers: 8
  split: val
  confidence_threshold: 0.5
  iou_threshold: 0.5
  nms_threshold: 0.5
  tracking_method: SORT
  track_iou_threshold: 0.5
  track_duration_threshold: 10
  track_max_age: 5
  duration_measurement_method: range
  correction_factor: 3.44