infer:
  dataset:
    name: paper_inference
    image_size: [224]
    len_clip: 32
    classes: ['Dancing']
    centered_clip: false
  model:
    name: 'yowo'
    backbone_2d:
      name: 'yolo_free_tiny'
      frozen: false
      pretrained: true
      stride: [ 8, 16, 32 ]
    backbone_3d:
      name: 'shufflenetv2'
      frozen: false
      pretrained: true
      memory_momentum: 0.9
      model_size: "2.0x"
    center_sampling_radius: 2.5
    confidence_threshold: 0.01
    nms_threshold: 0.3
    top_k: 10
    head_dim: 64
    head_norm: BN
    head_act: lrelu
    num_cls_heads: 2
    num_reg_heads: 2
    head_depthwise: false
    resume: C:\Users\CREST\Documents\GitHub\DeepWDT\runs\train\250715-183222-exotic-whale-9841\weights\epoch_20.pth
  device: cuda
  batch_size: 64
  num_workers: 8
  downscale_factor: 0.5
  confidence_threshold: 0.8
  nms_threshold: 0.5
  track_iou_threshold: 0.5
  track_duration_threshold: 10
  track_max_age: 5
  duration_measurement_method: range